apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-petclinic.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "spring-petclinic.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080